name: Release Tags

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  DOCKERFILE: Dockerfile
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Build and release stable image
    runs-on: ubuntu-latest
    env:
      REPOSITORY: local/kube-apps-httpcache
      TAG: "latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.RELEASE_USER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.RELEASE_USER_TOKEN }}

      - name: Scan for vulnerabilities
        uses: crazy-max/ghaction-container-scan@v3
        with:
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          dockerfile: ${{ env.DOCKERFILE }}
          severity: HIGH,CRITICAL
          # severity_threshold: HIGH
          annotations: true
